name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make
    
    - name: Tarball
      run: tar czvf ppa-utils.tar.gz build/*

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "ppa-utils.tar.gz"
